# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94031b38c623706194d8afe81ded7556397f77ae18f011d176169688f4acfe08a087c1083cda90672616df10072f3b4aae76cd53b0c582d1cc962d61ea9d484e

test:
  secret_key_base: 1cccabb2fe74ca1e97fc69bfc9264d377e8713c5b984e28f52a6bd62bcf20c3e7e8278270bf16f651324dbacc43a148ab1e1c48b2adb3fdd0ba5fd69c9e3a8cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
